# Generated by Django 5.1.4 on 2025-01-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('appointmentDateTime', models.DateTimeField()),
                ('doctor', models.CharField(max_length=255)),
                ('service', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('paymentScreenshot', models.ImageField(upload_to='payments/')),
            ],
        ),
    ]
