# Generated by Django 5.1.4 on 2025-01-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointmentDateTime',
            new_name='appointment_date_time',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='paymentScreenshot',
            new_name='payment_screenshot',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(max_length=100),
        ),
    ]
