# Generated by Django 5.1.4 on 2025-01-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('symptoms', models.TextField()),
                ('cure', models.TextField()),
                ('image', models.ImageField(upload_to='service_images/')),
            ],
        ),
    ]
