# Generated by Django 5.1.4 on 2025-01-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_aboutus_blogcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcard',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
