# Generated by Django 5.1.4 on 2025-01-15 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_clinic_servicehome'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clinic',
        ),
    ]
