# Generated by Django 5.1.4 on 2025-01-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_testimonial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.AlterField(
            model_name='bloghome',
            name='image',
            field=models.ImageField(upload_to='blogHome/'),
        ),
        migrations.AlterField(
            model_name='bloghome',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='imageslider',
            name='image',
            field=models.ImageField(upload_to='ImageSlider/'),
        ),
    ]
