# Generated by Django 5.1.4 on 2025-01-17 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_delete_address_alter_bloghome_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery-main/')),
            ],
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_date_time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(default=datetime.datetime(2025, 1, 17, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='time_slot',
            field=models.CharField(default=datetime.datetime(2025, 1, 17, 0, 0), max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payment_screenshots/'),
        ),
        migrations.AlterField(
            model_name='bloghome',
            name='image',
            field=models.ImageField(upload_to='blogs/'),
        ),
        migrations.AlterField(
            model_name='bloghome',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='imageslider',
            name='image',
            field=models.ImageField(upload_to='sliders/'),
        ),
    ]
