# Generated by Django 5.1.4 on 2025-01-17 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_gallerymain_remove_appointment_appointment_date_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='time_slot',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 17, 0, 0)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='payment_screenshot',
            field=models.ImageField(default=datetime.datetime(2025, 1, 17, 0, 0), upload_to='payments/'),
            preserve_default=False,
        ),
    ]
