# Generated by Django 5.1.4 on 2025-01-17 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_remove_appointment_appointment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerymain',
            name='alt_text',
            field=models.CharField(default=datetime.datetime(2025, 1, 17, 0, 0), max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gallerymain',
            name='image',
            field=models.ImageField(upload_to='gallery_images/'),
        ),
    ]
